name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Jest tests
        run: yarn test:nowatch

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: yarn run build
          start: yarn start
          browser: chrome

      - name: Publish test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./coverage

      - name: Check error
        if: failure()
        run: exit 1

      - name: Deploy to Firebase
        if: success() && github.ref == 'refs/heads/master'
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "REACT_APP_APP_ENV=${{ secrets.REACT_APP_APP_ENV }}" >> .env
          echo "REACT_APP_FIREBASE_BUCKET=${{ secrets.REACT_APP_FIREBASE_BUCKET }}" >> .env
          echo "REACT_APP_FIREBASE_CLIENT_EMAIL=${{ secrets.REACT_APP_FIREBASE_CLIENT_EMAIL }}" >> .env
          echo "REACT_APP_FIREBASE_PRIVATE_KEY=${{ secrets.REACT_APP_FIREBASE_PRIVATE_KEY }}" >> .env
          echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}" >> .env
          echo "REACT_APP_FACEBOOK_APP_ID=${{ secrets.REACT_APP_FACEBOOK_APP_ID }}" >> .env
          yarn global add firebase-tools
          yarn build
          echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > service-account-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$GITHUB_WORKSPACE/service-account-key.json"
          firebase deploy --only hosting
